<a href="https://colab.research.google.com/github/thilankam/AppInventorRaspberryPiCompanion/blob/master/pytorch_geometric_tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Add this in a Google Colab cell to install the correct version of Pytorch Geometric.
import torch

def format_pytorch_version(version):
  return version.split('+')[0]

TORCH_version = torch.__version__
TORCH = format_pytorch_version(TORCH_version)

def format_cuda_version(version):
  return 'cu' + version.replace('.', '')

CUDA_version = torch.version.cuda
CUDA = format_cuda_version(CUDA_version)

!pip install torch-scatter     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-sparse      -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-cluster     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-geometric 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://pytorch-geometric.com/whl/torch-1.12.0+cu113.html
     |████████████████████████████████| 7.9 MB 11.9 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://pytorch-geometric.com/whl/torch-1.12.0+cu113.html
     |████████████████████████████████| 3.5 MB 12.6 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://pytorch-geometric.com/whl/torch-1.12.0+cu113.html
     |████████████████████████████████| 2.4 MB 12.8 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://pytorch-geometric.com/whl/torch-1.12.0+cu113.html
     |████████████████████████████████| 709 kB 11.8 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.d

In [2]:
# Graph Neural Networks using PyG
# We will define the computation graph 
#import torch
import torch_geometric
from torch_geometric.datasets import Planetoid

Load th dataset

In [3]:
dataset = Planetoid(root="tutorial", name="Cora")

Processing...
Done!


Dataset Properties 

In [4]:
print(dataset)
print("number of graphs: \t\t", len(dataset))
print("number of classes: \t\t", dataset.num_classes)
print("number of node features: \t\t", dataset.num_node_features)
print("number of edge features: \t\t", dataset.num_edge_features)

Cora()
number of graphs: 		 1
number of classes: 		 7
number of node features: 		 1433
number of edge features: 		 0


In [5]:
print(dataset.data)

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])


In [17]:
print("edge_index:\t\t", dataset.data.edge_index.shape)
print(dataset.data.edge_index)
print("\n")
print("train_mask: \t\t",dataset.data.train_mask.shape)
print(dataset.data.train_mask)
print("\n")
print("x: \t\t", dataset.data.x.shape)
print(dataset.data.x)
print("\n")
print("y: \t\t", dataset.data.y.shape)
print("y: \t\t", dataset.data.y)

edge_index:		 torch.Size([2, 10556])
tensor([[   0,    0,    0,  ..., 2707, 2707, 2707],
        [ 633, 1862, 2582,  ...,  598, 1473, 2706]])


train_mask: 		 torch.Size([2708])
tensor([ True,  True,  True,  ..., False, False, False])


x: 		 torch.Size([2708, 1433])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


y: 		 torch.Size([2708])
y: 		 tensor([3, 4, 4,  ..., 3, 3, 3])


In [18]:
import os.path as osp
import torch
import torch.nn.functional as F 
